version = 0.1

[default.deploy.parameters]
stack_name = "hootner-platform"
resolve_s3 = true
s3_prefix = "hootner-platform"
region = "us-east-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
